version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker


      # specify any bash command here prefixed with `run: `
      
      - restore_cache:
            keys:
              - go-mod-v1-{{ checksum "go.sum" }}
      - run: 
          name: Test
          command: |
            go test ./...
      - run: 
          name: Lint
          command: |
            curl -L https://git.io/vp6lP | sh
            export PATH=$PATH:$PWD/bin
            gometalinter ./... 
      - run: 
          name: Code Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
      - run: 
          name: Build App
          command: |
            make build_local 
      - run:
          name: Build application Docker image
          command: |
            docker build -t jsenon/worker-ops:0.0.2 .
      - run: 
          name: DockerHub Login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push to registry
          command: |
            docker push $DOCKER_USER/worker-ops:0.0.2

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
